apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: weka-operator
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: weka-operator
  name: weka-operator-maintenance
